CREATE TABLE post_blobs (
    status_id VARCHAR(32) NOT NULL UNIQUE,
    json_body TEXT NOT NULL,

    -- System columns
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
