version: '3.9'

services:
  db:
    image: 'mariadb:11.6.2-noble'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_USER=mastdon_archiver
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=db
      - MARIADB_ROOT_PASSWORD=root

volumes:
  db-data:
