version: '3.9'

services:
  db:
    image: 'mariadb:11.6.2-noble'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_USER=mastodon_archiver
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=db
      - MARIADB_ROOT_PASSWORD=root
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

volumes:
  db-data:
